
export const SEARCH_CAMPAIGN="SEARCH_CAMPAIGN"
export const ADD_ONLIST="ADD_ONLIST"
export const REMOVE_ONE="REMOVE_ONE"
export const UPDATE_ONE="DONE_ONE"
export const ALL_DETAILS="ALL_DETAILS"
export const SEARCH_KEYWORD="SEARCH_KEYWORD"
export const BULK_UPDATE="BULK_UPDATE"